AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template facilitates the setup of an AWS API Gateway, 
  connecting it with a Virtual Private Cloud (VPC) and enabling access to microservices. 
  It also configures a CloudWatch Log Group for capturing API Gateway access logs. 
  The template includes parameters for customizing the environment and domain name, 
  making it easy to establish secure communication and monitor traffic.

Parameters:
  EnvironmentName:
    Description: An environment identifier added as a prefix to resource names (e.g., prod, test, dev)
    Type: String
  DomainName:
    Type: String
    Description: Domain Name for accessing the microservice through API Gateway

Resources:
  HttpApiVPCLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: !Sub ${EnvironmentName}-VpcLink
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}-FrontendSecroup
        - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSecroup
      SubnetIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet2

  CloudwatchAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${EnvironmentName}-apiGateway-accessLogs
      RetentionInDays: 7

Outputs:
  HttpApiVPCLinkId:
    Description: VPC Link from gateway to private subnets
    Value: !Ref HttpApiVPCLink
    Export:
      Name: !Sub ${EnvironmentName}-HttpApiVPCLinkId
  CloudwatchAccessLogGroupArn:
    Description: ARN of the CloudWatch access log group
    Value: !GetAtt CloudwatchAccessLogGroup.Arn
    Export:
      Name: !Sub ${EnvironmentName}-CloudwatchAccessLogGroupArn
