AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template simplifies the creation of AWS Elastic Container Registry repositories,
   providing secure storage for Docker images. 
   Each repository can be customized with a distinct name and includes image scanning configuration 
   to ensure enhanced security by performing scans when pushing new images.

Resources:

  ServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: <your repository name>
      ImageScanningConfiguration:
        ScanOnPush: true
