AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template automates the creation of DNS records for custom domain routing within the AWS environment. 
  It configures A records and alias targets for various environments, including production, test, development, and sandbox. 
  The template enables easy integration of custom domain names with AWS resources, such as API Gateway and CloudFront distributions.

Parameters:
  EnvironmentName:
    Description: A unique environment identifier used as a prefix for resource names (e.g., prod, test, dev)
    Type: String
  CertificateArn:
    Description: Amazon Resource Name (ARN) of the certificate
    Type: String
  DomainName:
    Type: String

Conditions:
  EnvironmentNameIsSandbox: !Equals [!Ref EnvironmentName, 'sandbox']
  EnvironmentNameIsDev: !Equals [!Ref EnvironmentName, 'dev']
  EnvironmentNameIsTest: !Equals [!Ref EnvironmentName, 'test']
  EnvironmentNameIsProd: !Equals [!Ref EnvironmentName, 'prod']

Resources:
  CustomDomainNameApiGateway:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref CertificateArn

  ProdProductsDnsRecord:
    Condition: EnvironmentNameIsProd
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          !GetAtt CustomDomainNameApiGateway.RegionalDomainName
        EvaluateTargetHealth: False
        HostedZoneId:
          !GetAtt CustomDomainNameApiGateway.RegionalHostedZoneId
      HostedZoneName: '<your domain>.'
      Comment: 'A records for <your domain>'
      Name: '<your domain>'
      Type: A

  ProdDocsDnsRecord:
    Condition: EnvironmentNameIsProd
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: 
          Fn::ImportValue: !Sub ${EnvironmentName}-cloudfront-DocsDistributionDomainName
        EvaluateTargetHealth: False
        HostedZoneId: 'Z2FDTNDATAQYW2'
      HostedZoneName: '<your domain>.'
      Comment: 'A records for docs.<your domain>'
      Name: 'docs.<your domain>'
      Type: A

  TestProductsDnsRecord:
    Condition: EnvironmentNameIsTest
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          !GetAtt CustomDomainNameApiGateway.RegionalDomainName
        EvaluateTargetHealth: False
        HostedZoneId:
          !GetAtt CustomDomainNameApiGateway.RegionalHostedZoneId
      HostedZoneName: 'test.<your domain>.'
      Comment: 'A records for <your domain>'
      Name: 'test.<your domain>'
      Type: A

  TestDocsDnsRecord:
    Condition: EnvironmentNameIsTest
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub ${EnvironmentName}-cloudfront-DocsDistributionDomainName
        EvaluateTargetHealth: False
        HostedZoneId: 'Z2FDTNDATAQYW2'
      HostedZoneName: 'test.<your domain>.'
      Comment: 'A records for docs.<your domain>'
      Name: 'docs.test.<your domain>'
      Type: A

  DevProductsDnsRecord:
    Condition: EnvironmentNameIsDev
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          !GetAtt CustomDomainNameApiGateway.RegionalDomainName
        EvaluateTargetHealth: False
        HostedZoneId:
          !GetAtt CustomDomainNameApiGateway.RegionalHostedZoneId
      HostedZoneName: 'dev.<your domain>.'
      Comment: 'A records for <your domain>'
      Name: 'dev.<your domain>'
      Type: A

  DevDocsDnsRecord:
    Condition: EnvironmentNameIsDev
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub ${EnvironmentName}-cloudfront-DocsDistributionDomainName
        EvaluateTargetHealth: False
        HostedZoneId: 'Z2FDTNDATAQYW2'
      HostedZoneName: 'dev.<your domain>.'
      Comment: 'A records for docs.<your domain>'
      Name: 'docs.dev.<your domain>'
      Type: A

  SandboxProductsDnsRecord:
    Condition: EnvironmentNameIsSandbox
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          !GetAtt CustomDomainNameApiGateway.RegionalDomainName
        EvaluateTargetHealth: False
        HostedZoneId:
          !GetAtt CustomDomainNameApiGateway.RegionalHostedZoneId
      HostedZoneName: 'sandbox.<your domain>.'
      Comment: 'A records for <your domain>'
      Name: 'sandbox.<your domain>'
      Type: A
