AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template facilitates the creation of Route 53 NS records, enabling domain routing across multiple AWS accounts. 
  By utilizing parameters such as the domain name and environment, these records offer seamless cross-account resolution for enhanced 
  resource access and management.

Parameters:
  DomainName:
    Description: The domain name to configure NS records for
    Type: String
  NsLookupRecords:
    Description: Nameserver lookup records for cross-account routing (e.g., prod, test, dev)
    Type: String

Resources:
  NsRouteToDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: '<your domain>.'
      Comment: !Sub NS Records for ${DomainName}
      Name: !Ref DomainName
      Type: NS
      TTL: 60
      ResourceRecords:
        Fn::Split:
          - ","
          - !Ref NsLookupRecords
