AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This CloudFormation template simplifies the creation of an AWS CloudFront distribution. 
  It offers an automated setup for distributing content globally with improved performance and security. 
  The template includes options for customizing domain names, SSL certificates, cache behavior, and origin configuration.

Parameters:
  EnvironmentName:
    Description: An environment identifier added as a prefix to resource names (e.g., prod, test, dev)
    Type: String
  DomainName:
    Description: Domain name associated with the distribution
    Type: String
  CertificateArn:
    Description: Amazon Resource Name (ARN) of the SSL certificate for the distribution
    Type: String

Resources:
  DocsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: !Sub ${EnvironmentName}-<your url>.s3-website.eu-central-1.amazonaws.com
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2and3
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            DomainName: !Sub ${EnvironmentName}-<your url>.s3-website.eu-central-1.amazonaws.com
            Id: !Sub ${EnvironmentName}-<your url>.s3-website.eu-central-1.amazonaws.com
            OriginPath: ''

Outputs:
  DocsDistributionId:
    Description: ID corresponding to the created distribution
    Value: !GetAtt DocsDistribution.Id
    Export:
      Name: !Sub ${AWS::StackName}-distributionId
  DocsDistributionDomainName:
    Description: Domain name associated with the distribution
    Value: !GetAtt DocsDistribution.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-distributionDomainName
