AWSTemplateFormatVersion: 2010-09-09
Description: >
  This AWS CloudFormation template facilitates the creation of CloudWatch alarms
   to monitor various events and conditions within an AWS environment. 
   The alarms help track critical events and notify subscribers via SNS topics. 
   Customizable parameters allow for flexible configuration.

Parameters:
  EnvironmentName:
    Description: An environment name that prefixes resource names (e.g., prod, test, or dev)
    Type: String

  LogGroupName:
    Type: String
    Default: CloudTrail/DefaultLogGroup
    Description: Enter CloudWatch Logs log group name. Default is CloudTrail/DefaultLogGroup

  ParanoiaLevel:
    Type: String
    Description: Level of alerting to use.
    Default: TopicAlertsNormal
    AllowedValues:
      - TopicAlertsNormal
      - TopicAlertsParanoid
      - TopicAlertsLax

  DashboardName:
    Type: String
    Description: Name of the Dashboard to create with the Alerts and Information
    Default: Security

  AccountDescription:
    Description: Identify this account in the notifications sent
    Type: String
    AllowedPattern: '[A-Za-z0-9]+'

  InitialSubscriberEmail:
    Description: Initial email to receive alerts
    Type: String
    Default: NONE

  BillingThreshold:
    Description: Sets the billing alert to trigger above this figure
    Type: Number
    Default: 0

Conditions:
  BillingAlarm: !Not [!Equals [!Ref BillingThreshold, 0]]
  EMailSubscription: !Not [!Equals [!Ref InitialSubscriberEmail, 'NONE']]

Resources:

  SNSAlertsCritical:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Critical Alerts for ", !Ref AccountDescription]]
      TopicName: !Join ['-', ["Critical-Alerts", !Ref AccountDescription]]

  SNSAlertsError:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Error Alerts for ", !Ref AccountDescription]]
      TopicName: !Join ['-', ["Error-Alerts", !Ref AccountDescription]]

  SNSAlertsInfo:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['', ["Info Alerts for ", !Ref AccountDescription]]
      TopicName: !Join ['-', ["Info-Alerts", !Ref AccountDescription]]

  SNSAlertPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: AlertTopicPolicy
        Version: 2012-10-17
        Statement:
          - Sid: My-statement-id
            Effect: Allow
            Principal:
              AWS: "*"
              # AWS: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':root']]
            Action: sns:Publish
            Resource: '*'
            Condition:
              StringEquals:
                AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - !Ref SNSAlertsCritical
        - !Ref SNSAlertsError
        - !Ref SNSAlertsInfo

  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: BillingAlarm
    Properties:
      AlarmDescription: !Sub "Alarm if AWS spending is over ${BillingThreshold}"
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: EUR
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: !Ref BillingThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref SNSAlertsError]
