AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template simplifies the creation of an AWS Cognito User Pool, 
  including a custom domain for authentication and user management. 
  The parameters allow customization of environment and domain names, 
  making it easy to establish user authentication and registration processes for different application environments.

Parameters:
  EnvironmentName:
    Description: An environment identifier added as a prefix to resource names (e.g., prod, test, dev)
    Type: String
  CognitoDomainName:
    Type: String
    Description: Custom domain name for Cognito user authentication

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      MfaConfiguration: 'OFF'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UserPoolName: cognito-apigateway
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
        InviteMessageTemplate:
          EmailSubject: Verify your email address
          EmailMessage: "< your message >" 
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: True
        DeviceOnlyRememberedOnUserPrompt: True
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      EmailVerificationSubject: Verify your email for ${ApplicationName}
      EmailVerificationMessage: Please click the link below to verify your email address. {####}

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref CognitoDomainName

Outputs:
  UserPoolId:
    Description: ID of the created Cognito User Pool
    Value: !Ref UserPool
    Export:
      Name: !Sub ${EnvironmentName}-UserPoolId
