AWSTemplateFormatVersion: 2010-09-09
Description: Identity Provider for Github Actions

Parameters:
  ThumbprintList:
    Type: String
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1
    Description: A thumbprint of an Open ID Connector is a SHA1 hash of the public certificate of the host

Resources:
  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - !Ref ThumbprintList
      Url: https://token.actions.githubusercontent.com

  GithubActionsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Github-Actions-Role
      Description: Allows Github Actions access
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GithubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:<your-github>*
              ForAllValues:StringEquals:
                token.actions.githubusercontent.com:iss: https://token.actions.githubusercontent.com
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Policies:
        - PolicyName: GitHubActions-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: # TODO: Tighten access to ecr and ecs
                  - ecr:*
                  - ecs:*
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:AbortMultipartUpload
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - lambda:UpdateFunctionCode
                  - lambda:ListFunctions
                  - lambda:InvokeFunction
                Resource:
                  - '*'
