AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for creating a private DNS namespace using AWS CloudMap for managed service discovery within a designated VPC environment.

Parameters:
  EnvironmentName:
    Description: A distinct environment identifier used as a prefix for resource names (e.g., prod, test, dev)
    Type: String
  PrivateDnsNamespace:
    Description: Name of the Private Hosted Zone for Namespace
    Type: String

Resources:
  PrivateDNSNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: CloudMap Private DNS Namespace for Service Discovery
      Vpc:
        Fn::ImportValue: !Sub ${EnvironmentName}-VpcId
      Name: !Ref PrivateDnsNamespace

Outputs:
  PrivateNamespaceARN:
    Description: Amazon Resource Name (ARN) of the Private DNS Namespace
    Value: !GetAtt PrivateDNSNamespace.Arn
  PrivateNamespaceID:
    Description: Identifier (ID) of the Private DNS Namespace
    Value: !GetAtt PrivateDNSNamespace.Id
    Export:
      Name: !Sub ${EnvironmentName}-PrivateDNSNamespaceId


