AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for creating a public hosted DNS zone using AWS Route 53

Parameters:
  EnvironmentName:
    Description: A unique environment identifier used as a prefix for resource names (e.g., prod, test, dev)
    Type: String
  DomainName:
    Type: String

Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: Public DNS zones for ${EnvironmentName} environment
      Name: !Ref DomainName

Outputs:
  PublicHostedZoneId:
    Description: ID of the created public hosted zone
    Value: !Ref PublicHostedZone
  HostedZoneNameServers:
    Description: Name servers associated with the hosted zone
    Value: !Join [',', !GetAtt PublicHostedZone.NameServers]

