AWSTemplateFormatVersion: 2010-09-09
Description: >
  This CloudFormation template streamlines the creation of an AWS Fargate Cluster, 
  providing a scalable environment for running containers through Amazon ECS. 
  Customizable parameters allow flexibility in specifying the environment name, 
  making it convenient to establish Fargate clusters for various application environments.

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-Fargate

Outputs:
  FargateCluster:
    Description: Fargate Cluster for ECS
    Value: !Ref Cluster
    Export:
      Name: !Sub ${EnvironmentName}-Fargate
